### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by j75** [kyron-security/FIC-2022#1]
Hello!

In README.md you stated `I will add the link to the MISC article as soon as it is published.` => isn't the link https://connect.ed-diamond.com/misc/misc-125/attaque-d-un-systeme-industriel actually?

**Comment by kyron-security** [comment]
Hello,
Exactly !
Thanks. I’ve updated the readme with the link ;)

Olivier Lévy
IT/OT Cybersecurity Expert
________________________________

[KYRON_2021n.png]

150, Rue Nicolas Louis Vauquelin
31100 Toulouse
Tél :

+33 534 478 665

Mobile :

+33 634 600 480

Email :

***@***.******@***.***>

Website :

https://www.kyron.fr

P Avant d'imprimer, merci de penser à l'environnement

On 20 Feb 2023, at 9:36 PM, j75 ***@***.***> wrote:



Hello!

In README.md you stated I will add the link to the MISC article as soon as it is published. => isn't the link https://connect.ed-diamond.com/misc/misc-125/attaque-d-un-systeme-industriel actually?
